### ISSUE TITLE
19.9.1 published without running the npm build

### ISSUE THREAD

**Issue by bibli-alex** [avadev/AvaTax-REST-V2-JS-SDK#96]
like: https://github.com/avadev/AvaTax-REST-V2-JS-SDK/issues/82
```
import client from './lib/AvaTaxClient';
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

**Comment by AndrewBarba** [comment]
And now 19.10 was also published without running the build script

**Comment by jwenger100** [comment]
newest version should not have this issue (22.5.0) please reopen if there is any further problems
